image: blondinal/inf3135:2020.2

stages:
    - build
    - test

build:
    stage: build
    script:
        - make

test:
    stage: test
    script:
        - make test
    artifacts:
        paths:
            - ./tests/isomap.png
