stages:
    - build
    - test

build:
    stage: build
    script:
        - apt-get update -qq
        - apt-get -y install libcairo2-dev
        - make

test:
    stage: test
    script:
        - build_root=$PWD
        - cd /tmp && git clone https://github.com/zorgnax/libtap.git && cd libtap && make && make install
        - ldconfig
        - cd $build_root
        - make test
