#include <jansson.h>

/**
 * Validation errors
 */
enum status {
    JSONVALIDATION_OK                           = 0,
    JSONVALIDATION_TOO_MANY_ROOT_OBJECTS        = 1,
    JSONVALIDATION_MISSING_TILEWIDTH_KEY        = 2,
    JSONVALIDATION_MISSING_ZOFFSET_KEY          = 3,
    JSONVALIDATION_MISSING_TILESET_KEY          = 4,
    JSONVALIDATION_MISSING_LAYERS_KEY           = 5,
    JSONVALIDATION_BAD_TILEWIDTH_VALUE          = 6,
    JSONVALIDATION_BAD_ZOFFSET_VALUE            = 7,
    JSONVALIDATION_MISSING_TILE_ID_KEY          = 8,
    JSONVALIDATION_MISSING_TILE_FILENAME_KEY    = 9,
    JSONVALIDATION_MISSING_INCOMING_KEY         = 10,
    JSONVALIDATION_MISSING_OUTGOING_KEY         = 11,
    JSONVALIDATION_BAD_TILE_ID_VALUE            = 12,
    JSONVALIDATION_BAD_TILE_FILENAME_VALUE      = 13,
    JSONVALIDATION_BAD_TILE_INCOMING_VALUE      = 14,
    JSONVALIDATION_BAD_TILE_OUTGOING_VALUE      = 15,
    JSONVALIDATION_MISSING_LAYER_NUMROWS_KEY    = 16,
    JSONVALIDATION_MISSING_LAYER_NUMCOLS_KEY    = 17,
    JSONVALIDATION_MISSING_LAYER_OFFSET_KEY     = 18,
    JSONVALIDATION_MISSING_LAYER_DATA_KEY       = 19,
    JSONVALIDATION_BAD_LAYER_NUMROWS_VALUE      = 20,
    JSONVALIDATION_BAD_LAYER_NUMCOLS_VALUE      = 21,
    JSONVALIDATION_BAD_LAYER_OFFSET_VALUE       = 22,
    JSONVALIDATION_BAD_LAYER_DATA_VALUE         = 23
};

// Validation functions //
// -------------------- //

